all:
	@time -p python main.py example.in example.out
	@echo ------------------------------------------------
	@time -p python main.py small.in small.out
	@echo ------------------------------------------------
#	@time -p python main.py medium.in medium.out
	@echo ------------------------------------------------
#	@time -p python main.py big.in big.out
	@echo ------------------------------------------------
clean:
	rm -f *.out
